services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_token_propagation
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    command: ["start-dev"]
  
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    env_file:
      - ./services/gateway/.env
    environment:
      BASE_URL: http://keycloak:8080
      JWKS_URL: http://keycloak:8080/realms/token-propagation/protocol/openid-connect/certs
      KEYCLOAK_AUTH_URL: http://keycloak:8080/realms/token-propagation/protocol/openid-connect/token
    container_name: gateway_service
    ports:
      - "8081:8081"
    depends_on:
      - keycloak

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    env_file:
      - ./services/users/.env
    environment:
      BASE_URL: http://keycloak:8080
      JWKS_URL: http://keycloak:8080/realms/token-propagation/protocol/openid-connect/certs
    expose:
      - "8082"
    depends_on:
      - keycloak

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    env_file:
      - ./services/orders/.env
    environment:
      BASE_URL: http://keycloak:8080
      JWKS_URL: http://keycloak:8080/realms/token-propagation/protocol/openid-connect/certs
    expose:
      - "8083"
    depends_on:
      - keycloak

volumes:
  keycloak_data: